DROP TABLE IF EXISTS TEMP.GUIDAPROMO;
CREATE TABLE TEMP.GUIDAPROMO AS
SELECT SUBSTR(A.`TB256-KEY`,28,4) AS FILIALE,
       SUBSTR(B.`TB256-KEY`,24,8) AS IDPROMO,
       SUBSTR(B.`TB256-SF-CAMPOALFA`, 4 , 8) AS DAL,
       SUBSTR(B.`TB256-SF-CAMPOALFA`, 13 , 8) AS AL,
       99   AS TREK
FROM  ARCHIVI.TABEL256 A
INNER JOIN ARCHIVI.TABEL256 B
ON    SUBSTR(A.`TB256-KEY` , 26 , 2) = SUBSTR(B.`TB256-SF-CAMPOALFA`, 1 , 2)
WHERE A.`TB256-23-TIPOTAB` = "ADERENTI"
AND   B.`TB256-23-TIPOTAB` = "CALOSGRU";
ALTER TABLE TEMP.GUIDAPROMO ADD PRIMARY KEY(FILIALE,IDPROMO),ENGINE=MYISAM;